### PR TITLE
Fix PBRify_Remix workflow + information

### PR DESCRIPTION
**Pull request by Kim2091**
This PR is to fix some basic issues in the workflow & condense it a bit. Additionally, it adds a link to detailed steps to set up and use the PBRify_Remix workflow.

Thank you very much for adding support initially 🙂

### CODE REVIEW

**Comment by nxkb** [comment]
No worries, and thanks for updating it! We fixed our CLA bot, would you mind the CLA for us? (you can just make a comment)

**Comment by Kim2091** [comment]
Hi, thank you for the response. I'm not really sure how to do the CLA? Sorry haha

**Comment by nxkb** [comment]
ah I was hoping a comment would trigger it, but I think you may have to rebase your changes and it should post instructions on here.

**Comment by Kim2091** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by sjgillard — APPROVED** [review]
Playing around with it seems to work well, and the docs look good to me!

**Pull request merged**
